# Generated by Django 4.1.4 on 2023-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_filtermodel_delete_namecoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coin', models.CharField(max_length=15, verbose_name='name coin')),
            ],
        ),
    ]
